# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default={'status': False, 'text': 'some text'})),
            ],
        ),
    ]
