# Generated by Django 4.2 on 2023-04-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.JSONField(default={'other_text': 'some other text', 'status': True})),
            ],
        ),
        migrations.AlterField(
            model_name='arrayjsonmodel',
            name='roles',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='RelatedJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_data', models.JSONField(default={'related_info': '', 'relevant': False})),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.otherjsonmodel')),
            ],
        ),
    ]
